[package]
name = "course"
version = "0.1.0"
edition = "2024"

[dependencies]
basics = { path = "../basics" }
myutils = { path = "../myutils" }
guessgame = { path = "../guessgame" }
intmut = { path = "../intmut" }